# Site settings
title: QinBlog
email: 1031219129@qq.com
url: https://Qinxiaoshou.github.io
description: "not thing is diffcult"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: QinPeiZhou

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
  - title: github
    url: https://Qinxiaoshou.github.io

# Build settings
markdown: kramdown
permalink: pretty
